services:
  express-api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8080:8080"
    
  ml-detection:
    build:
      context: .
      dockerfile: Dockerfile.ml
    depends_on:
      - express-api